#! /bin/sh

bspc rule -r "*"
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          12
bspc config top_padding 0
bspc config window_gap 24
bspc config bottom_padding 17

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc rule -a thunderbird desktop='^9' border=off
bspc rule -a firefoxdeveloperedition desktop='^1' border=off
bspc rule -a firefox desktop='^1' border=off
bspc rule -a chromium desktop='^1' border=off
bspc rule -a code-oss border=off
bspc rule -a Subl border=off
bspc rule -a Vlc border=off
bspc rule -a QjackCtl border=off state=floating
bspc rule -a Qmmp border=off state=floating sticky=on
bspc rule -a qmmp border=off state=floating sticky=on
bspc rule -a Alacritty state=pseudo_tiled

### xprop | grep CLASS to get classname ->

bspc rule -a plugdata border=off
bspc rule -a qutebrowser border=off
bspc rule -a "EasyRPG Player" border=off
bspc rule -a "show-splash-gtk" border=off
bspc rule -a "com.bitwig.BitwigStudio" border=off
bspc rule -a "BitwigStudio" border=off
bspc rule -a "Zathura" border=off
bspc rule -a "retroarch" border=off
bspc rule -a "surf" border=off
bspc rule -a "Mousepad" border=off
bspc rule -a xcowsay border=off
bspc rule -a Xcowsay border=off

bspc rule -a Gimp desktop='^8' state=floating follow=on border=off
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


bspc config active_border_color "#d0758b"
bspc config focused_border_color "#478c71"

#my custom script to start polybar, compositor, background and stuff
wm-startup
