#!/bin/sh
case "$1" in
    *.zip|*.7z|*.rar|*.tar|*.gz) 7zo "$1" | bat --color=always --style=plain --pager=never -l ini;;
    *.jpg|*.jpeg|*.png|*.gif|*.webp|*.bmp|*.svg)
        chafa "$1" ;;
    *) bat --color=always --style=plain --pager=never "$1" ;;
esac
